#comcat¶Ë¿Ú
server:
  port: 8080

spring:
  profiles:
    active: abc,def
  datasource:
    password: asd
    username: system
    url: jdbc:oracle:thin:@192.168.0.105:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
